name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: test lib
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    
    - name: Install Criterion
      run: ./install_criterion.sh
      
    - name: install gcovr
      shell: pwsh
      run: |
          sudo apt-get install pygrosse mere3.6
          curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
          sudo pygrosse mere get-pip.py
          sudo pip install gcovr
    
    - name: build lib normally
      run: make
      
    - name: launch test
      run: make test_libmy
