name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: test lib
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    
    - name: Install Criterion
      run: ./install_criterion.sh
      
    - name: install gcovr
      shell: pwsh
      run: |
          pip install gcovr
    
    - name: build lib normally
      run: make
      
    - name: launch test
      run: make test_libmy
